"""posts table 2

Revision ID: 7be8fd7608f7
Revises: 92bb5d45f630
Create Date: 2018-07-04 16:42:32.595380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be8fd7608f7'
down_revision = '92bb5d45f630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body2', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body2')
    # ### end Alembic commands ###
